# Generated by Django 3.2.6 on 2021-09-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
