# Generated by Django 3.2.6 on 2021-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='test_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
