# Generated by Django 3.2.6 on 2021-09-03 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('issue_type', models.CharField(choices=[('issue', 'Issue'), ('task', 'Task'), ('new feature', 'New Feature'), ('improvement', 'Improvement')], default='issue', max_length=30)),
                ('priority', models.CharField(choices=[('top', 'Top'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('work_effort_estimate', models.IntegerField()),
                ('work_effort_actual', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField()),
                ('assignee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('child_tasks', models.ManyToManyField(blank=True, related_name='parent_tasks', to='tracker.Issue')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
