# Generated by Django 3.2.6 on 2021-09-06 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_alter_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='leader',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
