# Generated by Django 3.2.6 on 2021-09-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210929_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-status', '-creation_date')},
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('1', 'Top'), ('2', 'High'), ('3', 'Medium'), ('4', 'Low')], default='medium', max_length=20),
        ),
    ]
