# Generated by Django 3.2.6 on 2021-09-03 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_alter_issue_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='auth.user'),
            preserve_default=False,
        ),
    ]
