# Generated by Django 3.2.6 on 2021-09-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_issue_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
