# Generated by Django 3.2.6 on 2021-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_issue_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('to_do', 'To-do'), ('in_progress', 'In progress'), ('in_review', 'In review'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
