# Generated by Django 3.2.6 on 2021-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210911_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fields',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
