# Generated by Django 3.2.6 on 2021-09-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_log_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.issue'),
        ),
        migrations.AlterField(
            model_name='log',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.project'),
        ),
    ]
