# Generated by Django 3.2.6 on 2021-09-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_log_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='fields',
        ),
    ]
