# Generated by Django 3.2.6 on 2021-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_log_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='fields',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
