# Generated by Django 3.2.6 on 2021-09-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_log_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='fields',
            new_name='removed_object',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='leader',
            new_name='creator',
        ),
    ]
