# Generated by Django 3.2.6 on 2021-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20210912_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Update'), ('delete', 'Delete')], max_length=50),
        ),
    ]
