# Generated by Django 3.2.6 on 2021-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_log_removed_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='No description provided.', max_length=1500),
        ),
    ]
