# Generated by Django 3.2.6 on 2021-09-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_timeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='work_effort_actual',
        ),
    ]
