# Generated by Django 3.2.6 on 2021-09-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20210921_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-creation_date',)},
        ),
    ]
